- name: Start kibana container
  docker_container:
    name: "ki01"
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.4.2"
    env:
      servername: "status.example.com"
      ELASTICSEARCH_HOSTS: "http://es01:9200"
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: "123"
    networks:
    - name: "esnet"
    
